# Configurations
title:            DNote
longtitle:        DNote_Notes
author:           dsx137
email:            
description: >
  Build Jekyll site with the GitBook style.

version:          1.0
gitbook_version:  3.2.3

repository:       dsx137/dsx137.github.io
github_url:       https://github.com/dsx137
url:              'https://dsx137.github.io'
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

#github
lsi: false
safe: true
source: ""
highlighter: rouge
gist:
  noscript: false

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: thankful_eyes

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
# permalink:        /:path/:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path
  posts:
    output: true
    permalink: /:collection/:path
  notes:
    output: true
    permalink: /:collection/:path
  

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  # - jekyll-readme-index
  - jemoji

defaults:
  - scope:
      path: "" # "" means all
    values:
      layout: post
  - scope:
      path: _notes
    values:
      layout: post