name: Deploy Docusaurus Github pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@main
      with:
        persist-credentials: false

    - name: Checkout submodules
      run: |
        git submodule update --init --recursive

    - name: Install and Build
      run: |
        npm install
        npm run-script build 

    - name: Copy old_jekyll content
      run: |
        cp -r ${{ github.workspace }}/build ${{ runner.temp }}

        git fetch origin gh-pages
        git checkout gh-pages
        
        if [ -d "${{ github.workspace }}/old_jekyll" ]; then
            cp -r ${{ github.workspace }}/old_jekyll ${{ runner.temp }}/build/
        else
            echo "old_jekyll directory does not exist, skipping copy."
        fi

        git checkout main
        
    - name: Deploy to Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ runner.temp }}/build
        publish_branch: gh-pages
        destination_dir: .

