name: Deploy Docusaurus Github pages
on:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false
          submodules: recursive

      - name: Set up pnpm
        run: corepack enable pnpm

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install and Build
        env:
          BASE_URL: /DNote/
        run: |
          pnpm install
          pnpm run build

      - name: Copy old_jekyll content
        run: |
          cp -r ${{ github.workspace }}/build ${{ runner.temp }}

          git checkout origin/gh-pages

          if [ -d "${{ github.workspace }}/old_jekyll" ]; then
              cp -r ${{ github.workspace }}/old_jekyll ${{ runner.temp }}/build/
          else
              echo "old_jekyll directory does not exist, skipping copy."
          fi

          git checkout main

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/build
          publish_branch: gh-pages
          destination_dir: .
